---
molecule_scenarios:
  - scenario: "default"
    ansible: ["previous", "current"]
    platforms:
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
      - "ubuntu2204"
      - "centos7"
      - "centos-stream8"
      - "ubi8"
      - "fedora35"
      - "fedora36"
      - "amazonlinux"
      - "rockylinux8"
      - "almalinux8"
