---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    mount_requests:
      - path: "/mnt/tmp"
        mode: "1777"
        src: "/tmp"
        fstype: "none"
        opts: "bind"

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
