---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    mount_requests:
      - path: "/mnt/tmp"
        mode: "1777"
        src: "/tmp"
        fstype: "none"
        opts: "bind"

  roles:
    - role: "ansible-role-mount"
